### ISSUE TITLE
No camera rendering on screen

### ISSUE THREAD

**Issue by KevPantelakis** [Redth/BigIslandBarcoding#2]
Hi, 

I know this is just a rough layout of the project, but after trying it, the camera does not seem to work for Android at least.

I got it to work by changing this line in the CameraManager.android.cs file:

```cs 
// The Context here SHOULD be something that's a lifecycle owner
	if (Context is AndroidX.Lifecycle.ILifecycleOwner lifecycleOwner)
		camera = cameraProvider.BindToLifecycle(lifecycleOwner, cameraSelector, cameraPreview, imageAnalyzer);
```
To
```cs 
// The Context here SHOULD be something that's a lifecycle owner
	if (Context.Context is AndroidX.Lifecycle.ILifecycleOwner lifecycleOwner)
		camera = cameraProvider.BindToLifecycle(lifecycleOwner, cameraSelector, cameraPreview, imageAnalyzer);
```

**Comment by mikecabana** [comment]
Have you tried this on a physical device or the emulator. Can't seem to get it to recognize a QR code through the emulator even after applying your fix.

Curious as well to the status of the project as to when it will be more or less production ready.

@Redth thanks for all your hard work!

**Comment by KevPantelakis** [comment]
@mikecabana 
I tried it on physical devices! It didn't work for me at first either so I skimmed through the code to find the reasons.
I got it to work by changing some things. First, I noticed that the options set in the sample project were not set in the ZXing object.

I fixed it by changing this line in CameraBarcodeReaderView.cs
```cs
public BarcodeReaderOptions Options
{
	get => (BarcodeReaderOptions)new BarcodeReaderOptions(); // GetValue(OptionsProperty);
	set => SetValue(OptionsProperty, value);
}
```
To
```cs
public BarcodeReaderOptions Options
{
	 get => (BarcodeReaderOptions)GetValue(OptionsProperty);
	set => SetValue(OptionsProperty, value);
}
```

Then I also noticed that scannerService was always reinstanciating the ZXingBarcodeReader. I also fixed that by changing this line in the HostBuilderExtensions.cs file:
```cs
.ConfigureServices(serviceCollection =>
{
    // Use default ZXing reader
    serviceCollection.AddTransient<Readers.IBarcodeReader, Readers.ZXingBarcodeReader>();
});
```
To
```cs
.ConfigureServices(serviceCollection =>
{
    // Use default ZXing reader
    serviceCollection.AddScoped<Readers.IBarcodeReader, Readers.ZXingBarcodeReader>();
});
```
These two fixes got it to work pretty good for me on android devices! I hope this helps you!

Also, @Redth Thanks for taking the time to start this port!

**Comment by Redth** [comment]
This is fixed in main now, thanks :)
